### ISSUE TITLE
For touchpad event, device type is set as IMDT_MOUSE

### ISSUE THREAD

**Issue by iamshivprasad** [chaopeng/IdentifyInputSource#1]
I'm trying out this application using VS 2019 (SDK version 10.0.19041.0, v142 toolset). It seems that input source for touchpad messages are not correctly identified by GetCurrentInputMessageSource(). I can see deviceType for touchpad messages are set as IMDT_MOUSE. Any idea why?

**Comment by chaopeng** [comment]
That is the reason I created this repo. I did ask [same question](https://github.com/microsoft/Windows-classic-samples/issues/18) but answer is intented. If you want to work on touchpad check this repo https://github.com/chaopeng/PTPDManipSample

**Comment by iamshivprasad** [comment]
Thank you. :)
